Repository mehalyna/Sf-069.Net-Project, pull requests merged in 2022-11, with the labels that each got.

#32 #29 unit tests
  SportsHub/.idea/.idea.SportsHub/.idea/.gitignore
  SportsHub/.idea/.idea.SportsHub/.idea/encodings.xml
  SportsHub/.idea/.idea.SportsHub/.idea/vcs.xml
  SportsHub/UnitTests/Controllers/UserControllerTests.cs
  SportsHub/UnitTests/DataLayerTests/GenericRepositoryTests.cs
  SportsHub/UnitTests/DataLayerTests/UnitOfWorkTests.cs
  SportsHub/UnitTests/MockData/UserMockData.cs
  SportsHub/UnitTests/Services/AuthenticationServiceTests.cs
  SportsHub/UnitTests/Services/UserServiceTests.cs
  SportsHub/UnitTests/UnitTests.csproj
Labels: task

#35 #28 technical debt
  SportsHub/SportsHub.Api/Controllers/LoginController.cs
  SportsHub/SportsHub.Api/Controllers/RegisterController.cs
  SportsHub/SportsHub.Api/Controllers/UserController.cs
  SportsHub/SportsHub.Api/Program.cs
  SportsHub/SportsHub.Core/Constants/ValidationMessages.cs
  SportsHub/SportsHub.DAL/Repository/GenericRepository.cs
  SportsHub/SportsHub.DAL/Repository/UserRepository.cs
Labels: Technical debt

#39 #33 retrieve all articles
  SportsHub/SportsHub.Api/Controllers/ArticleController.cs
  SportsHub/SportsHub.Api/Controllers/RegisterController.cs
  SportsHub/SportsHub.Api/Controllers/UserController.cs
  SportsHub/SportsHub.Application/Services/ArticleService.cs
  SportsHub/SportsHub.Application/Services/IArticleService.cs
  SportsHub/SportsHub.Core/Constants/ValidationMessages.cs
  SportsHub/SportsHub.Core/Repository/IArticleRepository.cs
  SportsHub/SportsHub.DAL/Repository/ArticleRepository.cs
  SportsHub/UnitTests/Controllers/ArticleControllerTests.cs
  SportsHub/UnitTests/Controllers/UserControllerTests.cs
  SportsHub/UnitTests/MockData/ArticleMockData.cs
  SportsHub/UnitTests/Services/AuthenticationServiceTests.cs
  SportsHub/UnitTests/UnitTests.csproj
Labels: task

#41 #40 ExtendExceptionHandler
  SportsHub/SportsHub.Api/Exceptions/ExceptionHandler.cs
  SportsHub/SportsHub.Application/Services/ArticleService.cs
  SportsHub/SportsHub.Application/Services/CommentService.cs
  SportsHub/SportsHub.Application/Services/UserService.cs
  SportsHub/SportsHub.Core/Models/Constants/ExceptionMessages.cs
  SportsHub/SportsHub.Core/Models/Constants/StatusCodeConstants.cs
  SportsHub/SportsHub.Core/Models/CustomExceptionModels/BaseCustomException.cs
  SportsHub/SportsHub.Core/Models/CustomExceptionModels/BusinessLogicException.cs
  SportsHub/SportsHub.Core/Models/CustomExceptionModels/NotFoundException.cs
Labels: task

#43 #42-DeleteArticle
  SportsHub/SportsHub.Api/Controllers/ArticleController.cs
  SportsHub/SportsHub.Application/Services/ArticleService.cs
  SportsHub/SportsHub.Application/Services/IArticleService.cs
  SportsHub/SportsHub.Core/Constants/ValidationMessages.cs
  SportsHub/SportsHub.Core/Repository/IArticleRepository.cs
  SportsHub/SportsHub.DAL/Repository/ArticleRepository.cs
  SportsHub/UnitTests/Services/ArticleServiceTests.cs
Labels: task

#56 Added AutoFixture
  SportsHub/UnitTests/Controllers/ArticleControllerTests.cs
  SportsHub/UnitTests/Controllers/UserControllerTests.cs
  SportsHub/UnitTests/DataLayerTests/GenericRepositoryTests.cs
  SportsHub/UnitTests/DataLayerTests/UnitOfWorkTests.cs
  SportsHub/UnitTests/MockData/ArticleMockData.cs
  SportsHub/UnitTests/MockData/UserMockData.cs
  SportsHub/UnitTests/Services/AuthenticationServiceTests.cs
  SportsHub/UnitTests/Services/UserServiceTests.cs
  SportsHub/UnitTests/UnitTests.csproj
Labels: Technical debt

#53 #52 add team and league models
  SportsHub/SportsHub.Core/Models/League.cs
  SportsHub/SportsHub.Core/Models/Sport.cs
  SportsHub/SportsHub.Core/Models/SubLeague.cs
  SportsHub/SportsHub.Core/Models/Team.cs
  SportsHub/SportsHub.DAL/Data/Configurations/ArticleEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/CategoryEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/CommentEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/Constants/ConfigurationConstants.cs
  SportsHub/SportsHub.DAL/Data/Configurations/LeagueEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/RoleEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/SportEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/StateEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/SubLeagueEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/TeamEntityTypeConfiguration.cs
  SportsHub/SportsHub.DAL/Data/Configurations/UserEntityTypeConfiguration.cs
Labels: task

#61 Fixed an error in main because of changes to config constants.
  SportsHub/SportsHub.Api/Validations/ArticleValidation.cs
Labels: bug
